# GPU-Enabled Multi-Worker Architecture
# 
# This docker-compose sets up:
# - Platform service (PaaS layer) with auth, billing, discovery, routing  
# - CPU-based workers (document, email, image classification)
# - GPU-accelerated image classifier (only on GPU-capable nodes)
# - Proper networking and GPU resource allocation
# - Zero-trust mTLS security for all services

services:
  # Platform Service (PaaS Layer) - HTTPS/mTLS ONLY
  platform:
    build:
      context: services
      dockerfile: Dockerfile.platform
    container_name: crank-platform
    ports:
      - "8443:8443"  # 🔒 HTTPS with mTLS ONLY
    volumes:
      - certs-volume:/etc/certs  # Share certificates with workers
    environment:
      - PLATFORM_ENV=docker
      - CRANK_ENVIRONMENT=production  # 🔒 HTTPS ONLY - no HTTP fallback
      - LOG_LEVEL=INFO
      - HTTPS_ONLY=true  # 🔒 Force HTTPS-only mode
    healthcheck:
      test: ["CMD", "curl", "--cacert", "/etc/certs/ca.crt", "--cert", "/etc/certs/client.crt", "--key", "/etc/certs/client.key", "-f", "https://localhost:8443/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - crank-net
    restart: unless-stopped

  # CPU Workers (Always available)
  
  # Crank Document Converter Worker
  crank-doc-converter:
    build:
      context: services
      dockerfile: Dockerfile.crank-doc-converter
    container_name: crank-doc-converter
    ports:
      - "8081:8081"
      - "8002:8443"  # Map to different external port to avoid conflict
    volumes:
      - certs-volume:/etc/certs  # Share certificates with platform
    environment:
      - PLATFORM_URL=https://platform:8443  # 🔒 ZERO-TRUST: Use HTTPS for platform communication
      - CRANK_ENVIRONMENT=development  # 🔒 Development with HTTPS testing
      - LOG_LEVEL=INFO
      - PLATFORM_AUTH_TOKEN=dev-mesh-key
    depends_on:
      platform:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - crank-net
    restart: unless-stopped

  # Crank Email Classifier Worker  
  crank-email-classifier:
    build:
      context: services
      dockerfile: Dockerfile.crank-email-classifier
    container_name: crank-email-classifier
    ports:
      - "8003:8003"
      - "8004:8443"  # Map to different external port to avoid conflict
    volumes:
      - certs-volume:/etc/certs  # Share certificates with platform
    environment:
      - PLATFORM_URL=https://platform:8443  # 🔒 ZERO-TRUST: Use HTTPS for platform communication
      - CRANK_ENVIRONMENT=development  # 🔒 Development with HTTPS testing
      - LOG_LEVEL=INFO
      - PLATFORM_AUTH_TOKEN=dev-mesh-key
    depends_on:
      platform:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s  # ML models need more time to initialize
    networks:
      - crank-net
    restart: unless-stopped

  # Crank Image Classifier Worker (CPU)
  crank-image-classifier:
    build:
      context: .
      dockerfile: image-classifier/Dockerfile
    container_name: crank-image-classifier
    ports:
      - "8005:8005"
      - "8006:8443"  # Map to different external port to avoid conflict
    volumes:
      - certs-volume:/etc/certs  # Share certificates with platform
    environment:
      - PLATFORM_URL=https://platform:8443  # 🔒 ZERO-TRUST: Use HTTPS for platform communication
      - CRANK_ENVIRONMENT=development  # 🔒 Development with HTTPS testing
      - LOG_LEVEL=INFO
      - PLATFORM_AUTH_TOKEN=dev-mesh-key
    depends_on:
      platform:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # Computer vision models need time to initialize
    networks:
      - crank-net
    restart: unless-stopped

  # GPU Workers (Only on GPU-capable nodes)

  # Crank GPU Image Classifier Worker
  crank-image-classifier-gpu:
    build:
      context: .
      dockerfile: image-classifier-gpu/Dockerfile
    container_name: crank-image-classifier-gpu
    ports:
      - "8007:8007"
      - "8008:8443"  # Map to different external port to avoid conflict
    volumes:
      - certs-volume:/etc/certs  # Share certificates with platform
    environment:
      - PLATFORM_URL=https://platform:8443  # 🔒 ZERO-TRUST: Use HTTPS for platform communication
      - CRANK_ENVIRONMENT=development  # 🔒 Development with HTTPS testing
      - LOG_LEVEL=INFO
      - PLATFORM_AUTH_TOKEN=dev-mesh-key
      - CUDA_VISIBLE_DEVICES=0  # Use first GPU
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      platform:
        condition: service_healthy
    healthcheck:
      test: |
        curl -f http://localhost:8007/health 2>/dev/null || 
        curl -k -f https://localhost:8008/health 2>/dev/null || 
        (echo "GPU image classifier health check failed on both HTTP and HTTPS" && exit 1)
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s  # GPU models need significant time to initialize
    networks:
      - crank-net
    restart: unless-stopped
    # GPU Configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia  # Requires nvidia-docker runtime

networks:
  crank-net:
    driver: bridge
    name: crank-network

volumes:
  platform-data:
    name: crank-platform-data
  certs-volume:
    name: crank-platform-certs