# Platform + Worker Architecture
# 
# This docker-compose sets up:
# - Platform service (PaaS layer) with auth, billing, discovery, routing
# - CrankDoc worker that registers with platform
# - Proper networking for service discovery

services:
  # Platform Service (PaaS Layer)
  platform:
    build:
      context: services
      dockerfile: Dockerfile.platform
    container_name: crank-platform
    ports:
      - "8080:8000"  # HTTP fallback for development
      - "8443:8443"  # HTTPS with mTLS for production
    volumes:
      - certs-volume:/etc/certs  # Share certificates with workers
    environment:
      - PLATFORM_ENV=docker
      - CRANK_ENVIRONMENT=development  # 🔒 Development with HTTPS testing
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/health/live"]  # 🔒 Use HTTPS health check
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - crank-net
    restart: unless-stopped

  # Crank Document Converter Worker
  crank-doc-converter:
    build:
      context: services
      dockerfile: Dockerfile.crank-doc-converter
    container_name: crank-doc-converter
    ports:
      - "8081:8081"
      - "8002:8443"  # Map to different external port to avoid conflict
    volumes:
      - certs-volume:/etc/certs  # Share certificates with platform
    environment:
      - PLATFORM_URL=https://platform:8443  # 🔒 ZERO-TRUST: Use HTTPS for platform communication
      - CRANK_ENVIRONMENT=development  # 🔒 Development with HTTPS testing
      - LOG_LEVEL=INFO
      - PLATFORM_AUTH_TOKEN=dev-mesh-key
    depends_on:
      platform:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - crank-net
    restart: unless-stopped

networks:
  crank-net:
    driver: bridge
    name: crank-network

volumes:
  platform-data:
    name: crank-platform-data
  certs-volume:
    name: crank-platform-certs