version: '3.8'

# Mac Docker Desktop Configuration  
# Optimized for Metal Performance Shaders and macOS integration

services:
  aiml-dev-metal:
    build: 
      context: .
      dockerfile: Dockerfile.mac
    image: aiml-hybrid-metal:latest
    container_name: aiml-dev-metal-mac
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
      - "8080:8080"  # Web apps
    volumes:
      - type: bind
        source: .
        target: /workspace
      - aiml-data-mac:/data
      - aiml-models-mac:/models
      - type: bind
        source: /Users
        target: /mac-users
        read_only: true
    environment:
      - PLATFORM=mac
      - METAL_DEVICE_WRAPPER_TYPE=1
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    stdin_open: true
    tty: true
    restart: unless-stopped

  aiml-dev-cpu:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    image: aiml-hybrid-cpu:latest
    container_name: aiml-dev-cpu-mac
    ports:
      - "8889:8888"  # Jupyter on different port
      - "6007:6006"  # TensorBoard on different port
    volumes:
      - type: bind
        source: .
        target: /workspace
      - aiml-data-mac:/data
      - type: bind
        source: /Users
        target: /mac-users
        read_only: true
    environment:
      - PLATFORM=mac
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  aiml-data-mac:
    driver: local
  aiml-models-mac:
    driver: local