from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PlatformServiceProtocol(Protocol):
    async def method(self, *args: Any, **kwargs: Any) -> Any: ...


@runtime_checkable
class ProtocolServiceProtocol(Protocol):
    async def get_supported_protocols(self) -> list[str]: ...
    async def mcp_list_tools(self) -> list[Mapping[str, Any]]: ...


@runtime_checkable
class DiscoveryServiceProtocol(Protocol):
    async def register_worker(self, *args: Any, **kwargs: Any) -> Any: ...
    async def heartbeat_worker(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update_worker_load(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_workers(self, *args: Any, **kwargs: Any) -> Any: ...
    async def route_request(self, *args: Any, **kwargs: Any) -> Any: ...
    async def cleanup(self) -> None: ...
